apiVersion: v1
kind: Service
metadata:
  name: courierservice
spec:
  type:  ClusterIP
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: courierservice
