apiVersion: apps/v1
kind: Deployment
metadata:
  name: courierservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: courierservice
  template:
    metadata:
      labels:
        app: courierservice
    spec:
      containers:
      - env:
        - name: DB_SERVER
          value: postgresqldb-courier
        - name: POSTGRES_DB
          value: courierservice
        - name: POSTGRES_PASSWORD
          value: "4526357"
        - name: POSTGRES_USER
          value: postgres
        image: mpinchuk/courierservice:latest
        imagePullPolicy: ""
        name: courierservice
        ports:
        - containerPort: 8082
