apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: postgresqldb-courier
  name: postgresqldb-courier
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresqldb-courier
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: postgresqldb-courier
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: courierservice
        - name: POSTGRES_PASSWORD
          value: "4526357"
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        imagePullPolicy: ""
        name: postgresqldb-courier
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postgres-data-courier
        persistentVolumeClaim:
          claimName: postgres-data-courier

status: {}
