apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresqldb-courier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresqldb-courier
  template:
    metadata:
      labels:
        app: postgresqldb-courier
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: courierservice
        - name: POSTGRES_PASSWORD
          value: "4526357"
        - name: POSTGRES_USER
          value: postgres
        image: postgres
        imagePullPolicy: ""
        name: postgresqldb-courier
        ports:
        - containerPort: 5432
